-- Initialize data for Symbol-Specific Thresholds System
-- This file will be executed after schema.sql to populate initial data
-- Update existing symbols with market_type
UPDATE
    symbols
SET
    market_type = 'US'
WHERE
    exchange IN ('NASDAQ', 'NYSE', 'AMEX');

UPDATE
    symbols
SET
    market_type = 'VN'
WHERE
    exchange IN ('HOSE', 'HNX', 'UPCOM');

-- Insert market threshold templates
INSERT INTO
    market_threshold_templates (
        market_type,
        strategy_name,
        description,
        is_default
    )
VALUES
    (
        'US',
        'MACD Zone Strategy US',
        'Default thresholds for US market stocks',
        TRUE
    ),
    (
        'VN',
        'MACD Zone Strategy VN',
        'Default thresholds for VN market stocks',
        TRUE
    ) ON DUPLICATE KEY
UPDATE
    description =
VALUES
(description),
    is_default =
VALUES
(is_default);

-- Get template IDs
SET
    @us_template_id = (
        SELECT
            id
        FROM
            market_threshold_templates
        WHERE
            market_type = 'US'
            AND strategy_name = 'MACD Zone Strategy US'
    );

SET
    @vn_template_id = (
        SELECT
            id
        FROM
            market_threshold_templates
        WHERE
            market_type = 'VN'
            AND strategy_name = 'MACD Zone Strategy VN'
    );

-- Market threshold template values for all timeframes
INSERT INTO
    market_threshold_template_values (
        template_id,
        timeframe,
        indicator,
        zone,
        comparison,
        min_value,
        max_value
    )
VALUES
    (
        @us_template_id,
        '1m',
        'fmacd',
        'igr',
        '>=',
        0.900000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'fmacd',
        'greed',
        '>=',
        0.660000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'fmacd',
        'bull',
        '>=',
        0.441000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'fmacd',
        'pos',
        '>=',
        0.300000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'fmacd',
        'neutral',
        '>=',
        0.222000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'fmacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'fmacd',
        'bear',
        '<',
        -0.222000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'fmacd',
        'fear',
        '<',
        -0.441000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'fmacd',
        'panic',
        '<',
        -0.900000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'igr',
        '>=',
        0.660000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'greed',
        '>=',
        0.441000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'bull',
        '>=',
        0.300000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'pos',
        '>=',
        0.222000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'neutral',
        '>=',
        0.141000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'bear',
        '<',
        -0.222000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'fear',
        '<',
        -0.441000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'smacd',
        'panic',
        '<',
        -0.660000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'bars',
        'Hurricane',
        '>=',
        0.900000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'bars',
        'Storm',
        '>=',
        0.660000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'bars',
        'StrongWind',
        '>=',
        0.441000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'bars',
        'Windy',
        '>=',
        0.300000,
        NULL
    ),
    (
        @us_template_id,
        '1m',
        'bars',
        'Neutral',
        '>=',
        0.222000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'igr',
        '>=',
        1.200000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'greed',
        '>=',
        0.880000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'bull',
        '>=',
        0.588000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'pos',
        '>=',
        0.400000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'neutral',
        '>=',
        0.296000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'bear',
        '<',
        -0.296000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'fear',
        '<',
        -0.588000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'fmacd',
        'panic',
        '<',
        -1.200000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'igr',
        '>=',
        0.880000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'greed',
        '>=',
        0.588000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'bull',
        '>=',
        0.400000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'pos',
        '>=',
        0.296000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'neutral',
        '>=',
        0.188000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'bear',
        '<',
        -0.296000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'fear',
        '<',
        -0.588000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'smacd',
        'panic',
        '<',
        -0.880000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'bars',
        'Hurricane',
        '>=',
        1.200000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'bars',
        'Storm',
        '>=',
        0.880000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'bars',
        'StrongWind',
        '>=',
        0.588000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'bars',
        'Windy',
        '>=',
        0.400000,
        NULL
    ),
    (
        @us_template_id,
        '2m',
        'bars',
        'Neutral',
        '>=',
        0.296000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'igr',
        '>=',
        1.500000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'greed',
        '>=',
        1.100000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'bull',
        '>=',
        0.735000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'pos',
        '>=',
        0.500000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'neutral',
        '>=',
        0.370000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'bear',
        '<',
        -0.370000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'fear',
        '<',
        -0.735000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'fmacd',
        'panic',
        '<',
        -1.500000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'igr',
        '>=',
        1.100000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'greed',
        '>=',
        0.735000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'bull',
        '>=',
        0.500000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'pos',
        '>=',
        0.370000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'neutral',
        '>=',
        0.235000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'bear',
        '<',
        -0.370000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'fear',
        '<',
        -0.735000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'smacd',
        'panic',
        '<',
        -1.100000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'bars',
        'Hurricane',
        '>=',
        1.500000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'bars',
        'Storm',
        '>=',
        1.100000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'bars',
        'StrongWind',
        '>=',
        0.735000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'bars',
        'Windy',
        '>=',
        0.500000,
        NULL
    ),
    (
        @us_template_id,
        '5m',
        'bars',
        'Neutral',
        '>=',
        0.370000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'igr',
        '>=',
        1.800000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'greed',
        '>=',
        1.320000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'bull',
        '>=',
        0.882000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'pos',
        '>=',
        0.600000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'neutral',
        '>=',
        0.444000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'bear',
        '<',
        -0.444000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'fear',
        '<',
        -0.882000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'fmacd',
        'panic',
        '<',
        -1.800000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'igr',
        '>=',
        1.320000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'greed',
        '>=',
        0.882000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'bull',
        '>=',
        0.600000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'pos',
        '>=',
        0.444000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'neutral',
        '>=',
        0.282000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'bear',
        '<',
        -0.444000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'fear',
        '<',
        -0.882000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'smacd',
        'panic',
        '<',
        -1.320000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'bars',
        'Hurricane',
        '>=',
        1.800000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'bars',
        'Storm',
        '>=',
        1.320000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'bars',
        'StrongWind',
        '>=',
        0.882000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'bars',
        'Windy',
        '>=',
        0.600000,
        NULL
    ),
    (
        @us_template_id,
        '15m',
        'bars',
        'Neutral',
        '>=',
        0.444000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'igr',
        '>=',
        2.100000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'greed',
        '>=',
        1.540000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'bull',
        '>=',
        1.029000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'pos',
        '>=',
        0.700000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'neutral',
        '>=',
        0.518000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'bear',
        '<',
        -0.518000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'fear',
        '<',
        -1.029000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'fmacd',
        'panic',
        '<',
        -2.100000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'igr',
        '>=',
        1.540000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'greed',
        '>=',
        1.029000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'bull',
        '>=',
        0.700000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'pos',
        '>=',
        0.518000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'neutral',
        '>=',
        0.329000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'bear',
        '<',
        -0.518000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'fear',
        '<',
        -1.029000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'smacd',
        'panic',
        '<',
        -1.540000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'bars',
        'Hurricane',
        '>=',
        2.100000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'bars',
        'Storm',
        '>=',
        1.540000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'bars',
        'StrongWind',
        '>=',
        1.029000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'bars',
        'Windy',
        '>=',
        0.700000,
        NULL
    ),
    (
        @us_template_id,
        '30m',
        'bars',
        'Neutral',
        '>=',
        0.518000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'igr',
        '>=',
        2.400000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'greed',
        '>=',
        1.760000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'bull',
        '>=',
        1.176000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'pos',
        '>=',
        0.800000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'neutral',
        '>=',
        0.592000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'bear',
        '<',
        -0.592000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'fear',
        '<',
        -1.176000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'fmacd',
        'panic',
        '<',
        -2.400000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'igr',
        '>=',
        1.760000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'greed',
        '>=',
        1.176000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'bull',
        '>=',
        0.800000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'pos',
        '>=',
        0.592000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'neutral',
        '>=',
        0.376000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'bear',
        '<',
        -0.592000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'fear',
        '<',
        -1.176000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'smacd',
        'panic',
        '<',
        -1.760000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'bars',
        'Hurricane',
        '>=',
        2.400000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'bars',
        'Storm',
        '>=',
        1.760000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'bars',
        'StrongWind',
        '>=',
        1.176000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'bars',
        'Windy',
        '>=',
        0.800000,
        NULL
    ),
    (
        @us_template_id,
        '1h',
        'bars',
        'Neutral',
        '>=',
        0.592000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'igr',
        '>=',
        2.700000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'greed',
        '>=',
        1.980000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'bull',
        '>=',
        1.323000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'pos',
        '>=',
        0.900000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'neutral',
        '>=',
        0.666000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'bear',
        '<',
        -0.666000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'fear',
        '<',
        -1.323000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'fmacd',
        'panic',
        '<',
        -2.700000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'igr',
        '>=',
        1.980000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'greed',
        '>=',
        1.323000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'bull',
        '>=',
        0.900000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'pos',
        '>=',
        0.666000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'neutral',
        '>=',
        0.423000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'bear',
        '<',
        -0.666000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'fear',
        '<',
        -1.323000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'smacd',
        'panic',
        '<',
        -1.980000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'bars',
        'Hurricane',
        '>=',
        2.700000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'bars',
        'Storm',
        '>=',
        1.980000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'bars',
        'StrongWind',
        '>=',
        1.323000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'bars',
        'Windy',
        '>=',
        0.900000,
        NULL
    ),
    (
        @us_template_id,
        '4h',
        'bars',
        'Neutral',
        '>=',
        0.666000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'igr',
        '>=',
        3.000000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'greed',
        '>=',
        2.200000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'bull',
        '>=',
        1.470000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'pos',
        '>=',
        1.000000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'neutral',
        '>=',
        0.740000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'bear',
        '<',
        -0.740000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'fear',
        '<',
        -1.470000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'fmacd',
        'panic',
        '<',
        -3.000000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'igr',
        '>=',
        2.200000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'greed',
        '>=',
        1.470000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'bull',
        '>=',
        1.000000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'pos',
        '>=',
        0.740000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'neutral',
        '>=',
        0.470000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'neg',
        '<',
        0.000000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'bear',
        '<',
        -0.740000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'fear',
        '<',
        -1.470000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'smacd',
        'panic',
        '<',
        -2.200000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'bars',
        'Hurricane',
        '>=',
        3.000000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'bars',
        'Storm',
        '>=',
        2.200000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'bars',
        'StrongWind',
        '>=',
        1.470000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'bars',
        'Windy',
        '>=',
        1.000000,
        NULL
    ),
    (
        @us_template_id,
        '1D',
        'bars',
        'Neutral',
        '>=',
        0.740000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'igr',
        '>=',
        15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'greed',
        '>=',
        9.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'bull',
        '>=',
        6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'pos',
        '>=',
        3.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'neg',
        '<',
        -3.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'bear',
        '<',
        -6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'fear',
        '<',
        -9.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'fmacd',
        'panic',
        '<',
        -15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'igr',
        '>=',
        13.500000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'greed',
        '>=',
        7.500000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'bull',
        '>=',
        4.500000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'pos',
        '>=',
        2.400000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'neg',
        '<',
        -2.400000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'bear',
        '<',
        -4.500000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'fear',
        '<',
        -7.500000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'smacd',
        'panic',
        '<',
        -13.500000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'bars',
        'Hurricane',
        '>=',
        4.500000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'bars',
        'Storm',
        '>=',
        3.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'bars',
        'StrongWind',
        '>=',
        1.800000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'bars',
        'Windy',
        '>=',
        0.900000,
        NULL
    ),
    (
        @vn_template_id,
        '1m',
        'bars',
        'Neutral',
        '>=',
        0.300000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'igr',
        '>=',
        20.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'greed',
        '>=',
        12.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'bull',
        '>=',
        8.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'pos',
        '>=',
        4.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'neg',
        '<',
        -4.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'bear',
        '<',
        -8.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'fear',
        '<',
        -12.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'fmacd',
        'panic',
        '<',
        -20.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'igr',
        '>=',
        18.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'greed',
        '>=',
        10.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'bull',
        '>=',
        6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'pos',
        '>=',
        3.200000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'neg',
        '<',
        -3.200000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'bear',
        '<',
        -6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'fear',
        '<',
        -10.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'smacd',
        'panic',
        '<',
        -18.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'bars',
        'Hurricane',
        '>=',
        6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'bars',
        'Storm',
        '>=',
        4.000000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'bars',
        'StrongWind',
        '>=',
        2.400000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'bars',
        'Windy',
        '>=',
        1.200000,
        NULL
    ),
    (
        @vn_template_id,
        '2m',
        'bars',
        'Neutral',
        '>=',
        0.400000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'igr',
        '>=',
        25.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'greed',
        '>=',
        15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'bull',
        '>=',
        10.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'pos',
        '>=',
        5.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'neg',
        '<',
        -5.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'bear',
        '<',
        -10.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'fear',
        '<',
        -15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'fmacd',
        'panic',
        '<',
        -25.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'igr',
        '>=',
        22.500000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'greed',
        '>=',
        12.500000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'bull',
        '>=',
        7.500000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'pos',
        '>=',
        4.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'neg',
        '<',
        -4.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'bear',
        '<',
        -7.500000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'fear',
        '<',
        -12.500000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'smacd',
        'panic',
        '<',
        -22.500000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'bars',
        'Hurricane',
        '>=',
        7.500000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'bars',
        'Storm',
        '>=',
        5.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'bars',
        'StrongWind',
        '>=',
        3.000000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'bars',
        'Windy',
        '>=',
        1.500000,
        NULL
    ),
    (
        @vn_template_id,
        '5m',
        'bars',
        'Neutral',
        '>=',
        0.500000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'igr',
        '>=',
        30.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'greed',
        '>=',
        18.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'bull',
        '>=',
        12.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'pos',
        '>=',
        6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'neg',
        '<',
        -6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'bear',
        '<',
        -12.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'fear',
        '<',
        -18.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'fmacd',
        'panic',
        '<',
        -30.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'igr',
        '>=',
        27.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'greed',
        '>=',
        15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'bull',
        '>=',
        9.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'pos',
        '>=',
        4.800000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'neg',
        '<',
        -4.800000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'bear',
        '<',
        -9.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'fear',
        '<',
        -15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'smacd',
        'panic',
        '<',
        -27.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'bars',
        'Hurricane',
        '>=',
        9.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'bars',
        'Storm',
        '>=',
        6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'bars',
        'StrongWind',
        '>=',
        3.600000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'bars',
        'Windy',
        '>=',
        1.800000,
        NULL
    ),
    (
        @vn_template_id,
        '15m',
        'bars',
        'Neutral',
        '>=',
        0.600000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'igr',
        '>=',
        35.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'greed',
        '>=',
        21.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'bull',
        '>=',
        14.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'pos',
        '>=',
        7.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'neg',
        '<',
        -7.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'bear',
        '<',
        -14.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'fear',
        '<',
        -21.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'fmacd',
        'panic',
        '<',
        -35.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'igr',
        '>=',
        31.500000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'greed',
        '>=',
        17.500000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'bull',
        '>=',
        10.500000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'pos',
        '>=',
        5.600000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'neg',
        '<',
        -5.600000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'bear',
        '<',
        -10.500000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'fear',
        '<',
        -17.500000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'smacd',
        'panic',
        '<',
        -31.500000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'bars',
        'Hurricane',
        '>=',
        10.500000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'bars',
        'Storm',
        '>=',
        7.000000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'bars',
        'StrongWind',
        '>=',
        4.200000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'bars',
        'Windy',
        '>=',
        2.100000,
        NULL
    ),
    (
        @vn_template_id,
        '30m',
        'bars',
        'Neutral',
        '>=',
        0.700000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'igr',
        '>=',
        40.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'greed',
        '>=',
        24.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'bull',
        '>=',
        16.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'pos',
        '>=',
        8.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'neg',
        '<',
        -8.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'bear',
        '<',
        -16.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'fear',
        '<',
        -24.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'fmacd',
        'panic',
        '<',
        -40.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'igr',
        '>=',
        36.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'greed',
        '>=',
        20.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'bull',
        '>=',
        12.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'pos',
        '>=',
        6.400000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'neg',
        '<',
        -6.400000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'bear',
        '<',
        -12.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'fear',
        '<',
        -20.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'smacd',
        'panic',
        '<',
        -36.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'bars',
        'Hurricane',
        '>=',
        12.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'bars',
        'Storm',
        '>=',
        8.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'bars',
        'StrongWind',
        '>=',
        4.800000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'bars',
        'Windy',
        '>=',
        2.400000,
        NULL
    ),
    (
        @vn_template_id,
        '1h',
        'bars',
        'Neutral',
        '>=',
        0.800000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'igr',
        '>=',
        45.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'greed',
        '>=',
        27.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'bull',
        '>=',
        18.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'pos',
        '>=',
        9.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'neg',
        '<',
        -9.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'bear',
        '<',
        -18.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'fear',
        '<',
        -27.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'fmacd',
        'panic',
        '<',
        -45.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'igr',
        '>=',
        40.500000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'greed',
        '>=',
        22.500000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'bull',
        '>=',
        13.500000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'pos',
        '>=',
        7.200000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'neg',
        '<',
        -7.200000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'bear',
        '<',
        -13.500000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'fear',
        '<',
        -22.500000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'smacd',
        'panic',
        '<',
        -40.500000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'bars',
        'Hurricane',
        '>=',
        13.500000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'bars',
        'Storm',
        '>=',
        9.000000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'bars',
        'StrongWind',
        '>=',
        5.400000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'bars',
        'Windy',
        '>=',
        2.700000,
        NULL
    ),
    (
        @vn_template_id,
        '4h',
        'bars',
        'Neutral',
        '>=',
        0.900000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'igr',
        '>=',
        50.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'greed',
        '>=',
        30.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'bull',
        '>=',
        20.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'pos',
        '>=',
        10.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'neg',
        '<',
        -10.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'bear',
        '<',
        -20.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'fear',
        '<',
        -30.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'fmacd',
        'panic',
        '<',
        -50.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'igr',
        '>=',
        45.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'greed',
        '>=',
        25.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'bull',
        '>=',
        15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'pos',
        '>=',
        8.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'neutral',
        '>=',
        0.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'neg',
        '<',
        -8.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'bear',
        '<',
        -15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'fear',
        '<',
        -25.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'smacd',
        'panic',
        '<',
        -45.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'bars',
        'Hurricane',
        '>=',
        15.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'bars',
        'Storm',
        '>=',
        10.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'bars',
        'StrongWind',
        '>=',
        6.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'bars',
        'Windy',
        '>=',
        3.000000,
        NULL
    ),
    (
        @vn_template_id,
        '1D',
        'bars',
        'Neutral',
        '>=',
        1.000000,
        NULL
    ) ON DUPLICATE KEY
UPDATE
    comparison =
VALUES
(comparison),
    min_value =
VALUES
(min_value),
    max_value =
VALUES
(max_value);

-- Create symbol-specific thresholds for all active symbols
INSERT INTO
    symbol_thresholds (symbol_id, market_type, strategy_name, is_active)
SELECT
    s.id as symbol_id,
    s.market_type,
    CASE
        WHEN s.market_type = 'US' THEN 'MACD Zone Strategy US'
        WHEN s.market_type = 'VN' THEN 'MACD Zone Strategy VN'
        ELSE 'MACD Zone Strategy US'
    END as strategy_name,
    TRUE as is_active
FROM
    symbols s
WHERE
    s.active = 1 ON DUPLICATE KEY
UPDATE
    market_type =
VALUES
(market_type),
    strategy_name =
VALUES
(strategy_name),
    is_active =
VALUES
(is_active);

-- Copy template values to symbol-specific thresholds
INSERT INTO
    symbol_threshold_values (
        symbol_threshold_id,
        timeframe,
        indicator,
        zone,
        comparison,
        min_value,
        max_value
    )
SELECT
    st.id as symbol_threshold_id,
    mtv.timeframe,
    mtv.indicator,
    mtv.zone,
    mtv.comparison,
    mtv.min_value,
    mtv.max_value
FROM
    symbol_thresholds st
    JOIN symbols s ON s.id = st.symbol_id
    JOIN market_threshold_templates mt ON mt.market_type = s.market_type
    AND mt.is_default = TRUE
    JOIN market_threshold_template_values mtv ON mt.id = mtv.template_id
WHERE
    st.is_active = TRUE ON DUPLICATE KEY
UPDATE
    comparison =
VALUES
(comparison),
    min_value =
VALUES
(min_value),
    max_value =
VALUES
(max_value);

-- Add some sample symbols if they don't exist
INSERT INTO
    symbols (ticker, exchange, currency, market_type, active)
VALUES
    -- US Stocks
    ('AAPL', 'NASDAQ', 'USD', 'US', 1),
    ('GOOGL', 'NASDAQ', 'USD', 'US', 1),
    ('MSFT', 'NASDAQ', 'USD', 'US', 1),
    ('TSLA', 'NASDAQ', 'USD', 'US', 1),
    ('AMZN', 'NASDAQ', 'USD', 'US', 1),
    ('META', 'NASDAQ', 'USD', 'US', 1),
    ('NVDA', 'NASDAQ', 'USD', 'US', 1),
    ('NFLX', 'NASDAQ', 'USD', 'US', 1),
    -- VN Stocks
    ('VIC', 'HOSE', 'VND', 'VN', 1),
    ('VCB', 'HOSE', 'VND', 'VN', 1),
    ('BID', 'HOSE', 'VND', 'VN', 1),
    ('CTG', 'HOSE', 'VND', 'VN', 1),
    ('TCB', 'HOSE', 'VND', 'VN', 1),
    ('MBB', 'HOSE', 'VND', 'VN', 1),
    ('VPB', 'HOSE', 'VND', 'VN', 1),
    ('STB', 'HOSE', 'VND', 'VN', 1),
    ('FPT', 'HOSE', 'VND', 'VN', 1),
    ('HPG', 'HOSE', 'VND', 'VN', 1),
    ('GAS', 'HOSE', 'VND', 'VN', 1),
    ('PLX', 'HOSE', 'VND', 'VN', 1) ON DUPLICATE KEY
UPDATE
    exchange =
VALUES
(exchange),
    currency =
VALUES
(currency),
    market_type =
VALUES
(market_type),
    active =
VALUES
(active);