version: 1.0
last_updated: '2025-01-27'
market: VN
description: "Vietnam Stock Market Configuration"
timezone: "Asia/Ho_Chi_Minh"
trading_hours:
  morning: "09:00-11:30"
  afternoon: "13:00-15:00"
  timezone: "Asia/Ho_Chi_Minh"

# Default configuration for Vietnamese stocks
default_indicators:
  macd:
    params:
      fast: 7
      slow: 113
      signal: 144
    # Lower thresholds for Vietnamese market (more volatile)
    default_thresholds:
      1m:
        bull: 0.15
        bear: -0.15
      2m:
        bull: 0.25
        bear: -0.25
      5m:
        bull: 0.35
        bear: -0.35
      15m:
        bull: 0.50
        bear: -0.50
      30m:
        bull: 0.75
        bear: -0.75
      1h:
        bull: 1.0
        bear: -1.0
      4h:
        bull: 1.5
        bear: -1.5

  sma:
    params:
      m1: 18
      m2: 36
      m3: 48
      ma144: 144
    timeframes:
      - 1m
      - 2m
      - 5m
      - 15m
      - 30m
      - 1h
      - 4h

# Sector-specific adjustments
sector_adjustments:
  banking:
    macd_multiplier: 1.2  # Higher thresholds for banking stocks
    description: "Banking stocks are more stable"
  
  real_estate:
    macd_multiplier: 0.9  # Lower thresholds for real estate
    description: "Real estate stocks are more volatile"
  
  steel:
    macd_multiplier: 1.3  # Higher thresholds for steel
    description: "Steel stocks have higher volatility"
  
  technology:
    macd_multiplier: 1.1  # Slightly higher thresholds
    description: "Tech stocks moderate volatility"
  
  index:
    macd_multiplier: 0.8  # Lower thresholds for indices
    description: "Indices are less volatile than individual stocks"

# Market-specific rules
market_rules:
  min_volume: 100000  # Minimum daily volume
  max_price_change: 0.07  # 7% daily limit
  circuit_breaker: 0.10  # 10% circuit breaker
  
# Risk management
risk_management:
  max_position_size: 0.1  # Max 10% of portfolio per stock
  stop_loss: 0.05  # 5% stop loss
  take_profit: 0.15  # 15% take profit
  
# Notification settings
notifications:
  telegram:
    enabled: true
    chat_id: "@vn_trading_signals"
  email:
    enabled: true
    recipients: ["trader@example.com"]
