version: 1.0
last_updated: '2025-01-27'
symbol: VCB
company: Vietcombank
weight: 1.0
sector: Banking
market: VN
indicators:
  macd:
    params:
      fast: 7
      slow: 113
      signal: 144
    thresholds:
      1m:
        bull: 0.12
        bear: -0.12
      2m:
        bull: 0.20
        bear: -0.20
      5m:
        bull: 0.30
        bear: -0.30
      15m:
        bull: 0.45
        bear: -0.45
      30m:
        bull: 0.65
        bear: -0.65
      1h:
        bull: 0.85
        bear: -0.85
      4h:
        bull: 1.25
        bear: -1.25
  sma:
    params:
      m1: 18
      m2: 36
      m3: 48
      ma144: 144
    timeframes:
      - 1m
      - 2m
      - 5m
      - 15m
      - 30m
      - 1h
      - 4h
