version: 1.0
last_updated: '2025-01-27'
symbol: VIC
company: Vingroup
weight: 1.0
sector: Real Estate
market: VN
indicators:
  macd:
    params:
      fast: 7
      slow: 113
      signal: 144
    thresholds:
      1m:
        bull: 0.18
        bear: -0.18
      2m:
        bull: 0.28
        bear: -0.28
      5m:
        bull: 0.42
        bear: -0.42
      15m:
        bull: 0.60
        bear: -0.60
      30m:
        bull: 0.85
        bear: -0.85
      1h:
        bull: 1.15
        bear: -1.15
      4h:
        bull: 1.70
        bear: -1.70
  sma:
    params:
      m1: 18
      m2: 36
      m3: 48
      ma144: 144
    timeframes:
      - 1m
      - 2m
      - 5m
      - 15m
      - 30m
      - 1h
      - 4h
